cafeteria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('api/core/', include('core.api_urls')),
    path('api/users/', include('users.api_urls')),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    
    path('produtos/', views.ProdutoListView.as_view(), name='produtos'),
    path('produtos/adicionar/', views.ProdutoCreateView.as_view(), name='produto_create'),
    path('produtos/<int:pk>/', views.ProdutoDetailView.as_view(), name='produto_detail'),
    path('produtos/editar/<int:pk>/', views.ProdutoUpdateView.as_view(), name='produto_update'),
    path('produtos/excluir/<int:pk>/', views.ProdutoDeleteView.as_view(), name='produto_delete'),
    
    path('categorias/', views.CategoriaListView.as_view(), name='categorias'),
    path('categorias/adicionar/', views.CategoriaCreateView.as_view(), name='categoria_create'),
    path('categorias/<int:pk>/', views.CategoriaDetailView.as_view(), name='categoria_detail'),
    path('categorias/editar/<int:pk>/', views.CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categorias/excluir/<int:pk>/', views.CategoriaDeleteView.as_view(), name='categoria_delete'),
    
    path('comandas/', views.ComandaListagemView.as_view(), name='comandas'),
    path('comandas/<int:pk>/', views.ComandaListView.as_view(), name='comanda_detail'),
    path('comandas/criar/', views.ComandaCreateView.as_view(), name='criar_comanda'),
    
    path('pedidos/', views.PedidosView.as_view(), name='pedidos'),
    path('pedidos/<int:pk>/', views.PedidosDetailView.as_view(), name='pedidos_detail'),
    path('pedidos/<int:comanda_id>/adicionar/<int:produto_id>/', views.AdicionarItemView.as_view(), name='adicionar_item'),
    path('pedidos/<int:comanda_id>/finalizar/', views.FinalizarComandaView.as_view(), name='finalizar_comanda'),
    path('pedidos/<int:comanda_id>/enviar-cozinha/', views.EnviarCozinhaView.as_view(), name='enviar_cozinha'),
    path('pedidos/<int:comanda_id>/pagamento/', views.ProcessarPagamentoView.as_view(), name='processar_pagamento'),
    
    path('mesas/', views.MesaListView.as_view(), name='mesas'),
    path('mesas/adicionar/', views.MesaCreateView.as_view(), name='mesa_create'),
    path('mesas/editar/<int:pk>/', views.MesaUpdateView.as_view(), name='mesa_update'),
    path('mesas/excluir/<int:pk>/', views.MesaDeleteView.as_view(), name='mesa_delete'),
]   

core/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from .models import *
from django.urls import reverse_lazy
from django.contrib import messages
from .permissions import GerenteRequiredMixin, AdminRequiredMixin, CaixaRequiredMixin


class DashboardView(LoginRequiredMixin, ListView):
    model = Produto
    template_name = 'core/dashboard.html'
    context_object_name = 'produtos'
    
    def get_queryset(self):
        return Produto.objects.filter(ativo=True)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        
        comandas_pagas = Comanda.objects.filter(status='PAGA')
        total_faturado = 0
        
        for comanda in comandas_pagas:
            total_faturado += comanda.total_geral
        
        context['total_faturado'] = total_faturado
        
        return context

class ProdutoListView(LoginRequiredMixin, ListView):
    model = Produto
    template_name = 'core/produtos/produtos.html'
    context_object_name = 'produtos'
    paginate_by = 12

    def get_queryset(self):
        queryset = Produto.objects.all()
        categoria_id = self.request.GET.get('categoria')
        if categoria_id:
            queryset = queryset.filter(categoria_id=categoria_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        return context

class ProdutoCreateView(LoginRequiredMixin, CreateView):
    model = Produto
    template_name = 'core/produtos/produto_form.html'
    fields = ['nome', 'descricao', 'preco', 'categoria', 'ativo']
    success_url = reverse_lazy('core:produtos')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Adicionar Produto'
        return context

class ProdutoUpdateView(LoginRequiredMixin, UpdateView): 
    model = Produto
    template_name = 'core/produtos/produto_edit.html'
    fields = ['nome', 'descricao', 'preco', 'categoria', 'ativo']
    success_url = reverse_lazy('core:produtos')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Produto'
        return context

class ProdutoDeleteView(LoginRequiredMixin, DeleteView):
    model = Produto
    template_name = 'core/produtos/produto_delete.html'
    success_url = reverse_lazy('core:produtos')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Excluir Produto'
        return context

class ProdutoDetailView(LoginRequiredMixin, DetailView):
    model = Produto
    template_name = 'core/produtos/produto_detail.html'
    context_object_name = 'produto'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['produtos'] = self.object.produto_set.all()
        return context


class CategoriaListView(LoginRequiredMixin, ListView):
    model = Categoria
    template_name = 'core/categorias/categorias.html'
    context_object_name = 'categorias'
    paginate_by = 12

class CategoriaCreateView(LoginRequiredMixin, CreateView):
    model = Categoria
    template_name = 'core/categorias/categoria_form.html'
    fields = ['nome', 'descricao', 'ativo']
    success_url = reverse_lazy('core:categorias')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Adicionar Categoria'
        return context

class CategoriaUpdateView(LoginRequiredMixin, UpdateView):
    model = Categoria
    template_name = 'core/categorias/categoria_form.html'
    fields = ['nome', 'descricao', 'ativo']
    success_url = reverse_lazy('core:categorias')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Categoria'
        return context

class CategoriaDeleteView(LoginRequiredMixin, DeleteView): 
    model = Categoria
    template_name = 'core/categorias/categoria_delete.html'
    success_url = reverse_lazy('core:categorias')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Excluir Categoria'
        return context


class CategoriaDetailView(LoginRequiredMixin, DetailView):
    model = Categoria
    template_name = 'core/categorias/categoria_detail.html'
    context_object_name = 'categoria'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = self.object.produto_set.all()
        return context

class ComandaCreateView(LoginRequiredMixin, CreateView):
    model = Comanda
    template_name = 'core/comandas/criar_comanda.html'
    fields = ['origem', 'mesa', 'observacao']
    success_url = reverse_lazy('core:pedidos')
    
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        form.instance.codigo = Comanda.objects.count() + 1
        response = super().form_valid(form)
        
        if form.instance.mesa:
            form.instance.mesa.status = 'OCUPADA'
            form.instance.mesa.save()
        
        self.request.session['comanda_atual'] = self.object.id
        messages.success(self.request, f'Comanda {self.object.codigo} criada!')
        return redirect('core:comanda_detail', pk=self.object.id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mesas'] = Mesa.objects.filter(status='LIVRE')
        return context
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if 'mesa' in form.fields:
            form.fields['mesa'].queryset = Mesa.objects.filter(status='LIVRE')
        return form

class ComandaListView(LoginRequiredMixin, DetailView):
    model = Comanda
    template_name = 'core/comandas/comanda_detail.html'
    context_object_name = 'comanda'
    
    def get_object(self):
        comanda_id = self.kwargs.get('pk')
        if comanda_id:
            return get_object_or_404(Comanda, id=comanda_id)
        return None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object:
            context['produtos'] = Produto.objects.filter(ativo=True)
            context['categorias'] = Categoria.objects.filter(ativo=True)
            context['itens_comanda'] = self.object.itemcomanda_set.all()
        return context

class ComandaListagemView(LoginRequiredMixin, ListView):
    model = Comanda
    template_name = 'core/comandas/listar_comandas.html'
    context_object_name = 'comandas'
    ordering = ['-created_at']
    
    def get_queryset(self):
        return Comanda.objects.filter(usuario=self.request.user)

class PedidosDetailView(LoginRequiredMixin, DetailView):
    model = Comanda
    template_name = 'core/pedidos/pedidos.html'
    context_object_name = 'comanda'
    
    def get_object(self):
        comanda_id = self.kwargs.get('pk') or self.request.session.get('comanda_atual')
        if comanda_id:
            return get_object_or_404(Comanda, id=comanda_id)
        return None
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['produtos'] = Produto.objects.filter(ativo=True)
        context['categorias'] = Categoria.objects.filter(ativo=True)
        context['itens_comanda'] = self.object.itemcomanda_set.all() if self.object else []
        return context

class AdicionarItemView(LoginRequiredMixin, CreateView):
    model = ItemComanda
    template_name = 'core/pedidos/adicionar_item.html'
    fields = ['quantidade', 'observacao']
    
    def form_valid(self, form):
        """Processa quando formulário é válido"""
        comanda_id = self.kwargs.get('comanda_id')
        produto_id = self.kwargs.get('produto_id')
        
        comanda = get_object_or_404(Comanda, id=comanda_id)
        produto = get_object_or_404(Produto, id=produto_id)
        
        form.instance.comanda = comanda
        form.instance.produto = produto
        
        item_existente = ItemComanda.objects.filter(
            comanda=comanda, 
            produto=produto
        ).first()
        
        if item_existente:
            item_existente.quantidade += form.instance.quantidade
            item_existente.save()
            messages.success(self.request, f'{produto.nome} adicionado à comanda!')
        else:
            form.save()
            messages.success(self.request, f'{produto.nome} adicionado à comanda!')
        
        return redirect('core:comanda_detail', pk=comanda_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        produto_id = self.kwargs.get('produto_id')
        context['produto'] = get_object_or_404(Produto, id=produto_id)
        return context

class FinalizarComandaView(LoginRequiredMixin, View):
    def post(self, request, comanda_id):
        comanda = get_object_or_404(Comanda, id=comanda_id)
        comanda.status = 'FECHADA'
        comanda.save()
        
        if comanda.mesa:
            comanda.mesa.status = 'LIVRE'
            comanda.mesa.save()
        
        request.session.pop('comanda_atual', None)
        messages.success(request, f'Comanda {comanda.codigo} finalizada!')
        return redirect('core:comandas')

class ProcessarPagamentoView(LoginRequiredMixin, View):
    def get(self, request, comanda_id):
        comanda = get_object_or_404(Comanda, id=comanda_id)

core/templates/core/mesas/mesa_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ title }} - Café Control{% endblock %}
{% block page_title %}{{ title }}{% endblock %}

{% block content %}
<div class="simple-form">
    <h3>{{ title }}</h3>
    
    <div class="alert alert-danger">
        <h5>Tem certeza que deseja excluir a mesa "{{ object.numero }}"?</h5>
        <p>Esta ação não pode ser desfeita.</p>
    </div>
    
    <form method="post">
        {% csrf_token %}
        
        <div class="form-actions">
            <a href="{% url 'core:mesas' %}" class="btn-cancel">Cancelar</a>
            <button type="submit" class="btn-delete">Excluir</button>
        </div>
    </form>
</div>
{% endblock %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/produto_form.css' %}">
{% endblock %}

core/templates/core/mesas/mesa_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}{{ title }} - Café Control{% endblock %}
{% block page_title %}{{ title }}{% endblock %}

{% block content %}
<div class="simple-form">
    <h3>{{ title }}</h3>
    
    <form method="post">
        {% csrf_token %}
        
        <div class="form-field">
            <label for="{{ form.numero.id_for_label }}">Número da Mesa *</label>
            {{ form.numero }}
            {% if form.numero.errors %}
                <div class="error">{{ form.numero.errors }}</div>
            {% endif %}
        </div>

        <div class="form-field">
            <label for="{{ form.status.id_for_label }}">Status *</label>
            {{ form.status }}
            {% if form.status.errors %}
                <div class="error">{{ form.status.errors }}</div>
            {% endif %}
        </div>

        <div class="form-actions">
            <a href="{% url 'core:mesas' %}" class="btn-cancel">Cancelar</a>
            <button type="submit" class="btn-save">Salvar</button>
        </div>
    </form>
</div>
{% endblock %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/produto_form.css' %}">
{% endblock %}

core/templates/core/mesas/mesas.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Mesas - Café Control{% endblock %}
{% block page_title %}Mesas{% endblock %}

{% block content %}
<div class="simple-form">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h3>Gerenciar Mesas</h3>
        <a href="{% url 'core:mesa_create' %}" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Nova Mesa
        </a>
    </div>

    {% if mesas %}
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Número</th>
                        <th>Status</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mesa in mesas %}
                        <tr>
                            <td>{{ mesa.numero }}</td>
                            <td>
                                <span class="badge {% if mesa.status == 'LIVRE' %}bg-success{% elif mesa.status == 'OCUPADA' %}bg-warning{% else %}bg-info{% endif %}">
                                    {{ mesa.get_status_display }}
                                </span>
                            </td>
                            <td>
                                <a href="{% url 'core:mesa_update' mesa.pk %}" class="btn btn-sm btn-outline-primary">
                                    <i class="bi bi-pencil"></i> Editar
                                </a>
                                <a href="{% url 'core:mesa_delete' mesa.pk %}" class="btn btn-sm btn-outline-danger">
                                    <i class="bi bi-trash"></i> Excluir
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="text-center py-5">
            <i class="bi bi-table" style="font-size: 4rem; color: #6c757d;"></i>
            <h4 class="mt-3 text-muted">Nenhuma mesa encontrada</h4>
            <p class="text-muted">Crie sua primeira mesa para começar!</p>
            <a href="{% url 'core:mesa_create' %}" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Criar Primeira Mesa
            </a>
        </div>
    {% endif %}
</div>
{% endblock %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/produto_form.css' %}">
{% endblock %}